import { 
    PlaySkip, PlayTop, AutoPlay, Join, Leave, Play, Queue, 
    GoLive, Loop, Skip, Clear, Previous, Pause, TwentyFourSeven, 
    Volume, Shuffle, Replay, EndLive, Bass, Normal, Earrape, 
    BassBoost, China, Chipmunk, Dance, Darthvader, EightD, 
    Jazz, Nightcore, Pop, SlowMotion, Soft, SuperBass, 
    Television, TrebleBass, Tremolo, Vaporwave, Vibrate, 
    Vibrato, Console 
} from '../components';

export const COMPONENT_MAP = {
    console: Console,
    join: Join,
    leave: Leave,
    play: Play,
    autoplay: AutoPlay,
    queue: Queue,
    golive: GoLive,
    loop: Loop,
    skip: Skip,
    clear: Clear,
    previous: Previous,
    pause: Pause,
    twentyfourseven: TwentyFourSeven,
    volume: Volume,
    shuffle: Shuffle,
    replay: Replay,
    endlive: EndLive,
    bass: Bass,
    normal: Normal,
    earrape: Earrape,
    bassboost: BassBoost,
    china: China,
    chipmunk: Chipmunk,
    dance: Dance,
    darthvader: Darthvader,
    eightd: EightD,
    jazz: Jazz,
    nightcore: Nightcore,
    pop: Pop,
    slowmotion: SlowMotion,
    soft: Soft,
    superbass: SuperBass,
    television: Television,
    treblebass: TrebleBass,
    tremolo: Tremolo,
    vaporwave: Vaporwave,
    vibrate: Vibrate,
    vibrato: Vibrato,
    playskip: PlaySkip,
    playtop: PlayTop
}; 