name: Build/Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install snapcraft (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo snap install snapcraft --classic
          sudo snap install core

      - name: Cleanup previous builds
        if: runner.os == 'Windows'
        run: |
          taskkill /F /IM 7za.exe || true
          if exist dist rmdir /S /Q dist
          if exist out rmdir /S /Q out
        shell: cmd

      - name: Cleanup previous builds (Unix)
        if: runner.os != 'Windows'
        run: |
          pkill -f 7za || true
          rm -rf dist out

      - name: Install dependencies
        run: npm ci

      - name: Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
        env:
          GH_TOKEN: ${{ secrets.github_token }}
          ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true 